const THProvinceList = [
    // ภาคเหนือ
    { th_name: "เชียงใหม่", en_name: "Chiang Mai", value_id: "101", disabled: false },
    { th_name: "แม่ฮ่องสอน", en_name: "Mae Hong Son", value_id: "102", disabled: false },
    { th_name: "เชียงราย", en_name: "Chiang Rai", value_id: "103", disabled: false },
    { th_name: "ลำพูน", en_name: "Lamphun", value_id: "104", disabled: false },
    { th_name: "ลำปาง", en_name: "Lampang", value_id: "105", disabled: false },
    { th_name: "พะเยา", en_name: "Phayao", value_id: "106", disabled: false },
    { th_name: "แพร่", en_name: "Phrae", value_id: "107", disabled: false },
    { th_name: "น่าน", en_name: "Nan", value_id: "108", disabled: false },
    { th_name: "อุตรดิตถ์", en_name: "Uttaradit", value_id: "109", disabled: false },
    { th_name: "ตาก", en_name: "Tak", value_id: "110", disabled: false },
    { th_name: "สุโขทัย", en_name: "Sukhothai", value_id: "111", disabled: false },
    { th_name: "พิษณุโลก", en_name: "Phitsanulok", value_id: "112", disabled: false },
    { th_name: "กำแพงเพชร", en_name: "Kamphaeng Phet", value_id: "113", disabled: false },
    { th_name: "เพชรบูรณ์", en_name: "Phetchabun", value_id: "114", disabled: false },
    { th_name: "พิจิตร", en_name: "Phichit", value_id: "115", disabled: false },

    // ภาคตะวันออกเฉียงเหนือ
    { th_name: "กาฬสินธุ์", en_name: "Kalasin", value_id: "201", disabled: false },
    { th_name: "ขอนแก่น", en_name: "Khon Kaen", value_id: "202", disabled: false },
    { th_name: "ชัยภูมิ", en_name: "Chaiyaphum", value_id: "203", disabled: false },
    { th_name: "นครพนม", en_name: "Nakhon Phanom", value_id: "204", disabled: false },
    { th_name: "นครราชสีมา", en_name: "Nakhon Ratchasima", value_id: "205", disabled: true },
    { th_name: "บุรีรัมย์", en_name: "Buri Ram", value_id: "206", disabled: false },
    { th_name: "มหาสารคาม", en_name: "Maha Sarakham", value_id: "207", disabled: false },
    { th_name: "มุกดาหาร", en_name: "Mukdahan", value_id: "208", disabled: false },
    { th_name: "ยโสธร", en_name: "Yasothon", value_id: "209", disabled: false },
    { th_name: "ร้อยเอ็ด", en_name: "Roi Et", value_id: "210", disabled: false },
    { th_name: "เลย", en_name: "Loei", value_id: "211", disabled: false },
    { th_name: "ศรีสะเกษ", en_name: "Si Sa Ket", value_id: "212", disabled: false },
    { th_name: "สกลนคร", en_name: "Sakon Nakhon", value_id: "213", disabled: false },
    { th_name: "สุรินทร์", en_name: "Surin", value_id: "214", disabled: false },
    { th_name: "หนองคาย", en_name: "Nong Khai", value_id: "215", disabled: false },
    { th_name: "หนองบัวลำภู", en_name: "Nong Bua Lam Phu", value_id: "216", disabled: false },
    { th_name: "อุดรธานี", en_name: "Udon Thani", value_id: "217", disabled: false },
    { th_name: "อุบลราชธานี", en_name: "Ubon Ratchathani", value_id: "218", disabled: false },
    { th_name: "อำนาจเจริญ", en_name: "Amnat Charoen", value_id: "219", disabled: false },

    // ภาคกลาง
    { th_name: "กรุงเทพมหานคร", en_name: "Bangkok", value_id: "301", disabled: false },
    { th_name: "อุทัยธานี", en_name: "Uthai Thani", value_id: "302", disabled: false },
    { th_name: "ชัยนาท", en_name: "Chai Nat", value_id: "303", disabled: false },
    { th_name: "นครสวรรค์", en_name: "Nakhon Sawan", value_id: "304", disabled: false },
    { th_name: "นนทบุรี", en_name: "Nonthaburi", value_id: "305", disabled: false },
    { th_name: "ปทุมธานี", en_name: "Pathum Thani", value_id: "306", disabled: false },
    { th_name: "พระนครศรีอยุธยา", en_name: "Phra Nakhon Si Ayutthaya", value_id: "307", disabled: false },
    { th_name: "ลพบุรี", en_name: "Lop Buri", value_id: "308", disabled: false },
    { th_name: "สมุทรปราการ", en_name: "Samut Prakan", value_id: "309", disabled: false },
    { th_name: "สมุทรสงคราม", en_name: "Samut Songkhram", value_id: "310", disabled: false },
    { th_name: "สมุทรสาคร", en_name: "Samut Sakhon", value_id: "311", disabled: false },
    { th_name: "สระบุรี", en_name: "Saraburi", value_id: "312", disabled: false },
    { th_name: "สิงห์บุรี", en_name: "Sing Buri", value_id: "313", disabled: false },
    { th_name: "อ่างทอง", en_name: "Ang Thong", value_id: "314", disabled: false },

];
